#!/bin/sh
[ "$DEBUG" = "1" ] && set -xe

if [ $(pgrep -u "$(id -un)" -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

. "$(dirname "$0")/panel_config"

bspc config top_padding 20
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0 

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &

#clock -sf 'C%a %d-%b %H:%M' > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#xprop -spy -root _NET_ACTIVE_WINDOW | sed -un 's/.*\(0x.*\)/A\1/p' > "$PANEL_FIFO" &

# create the toggle file before running this conky
~/.config/lemonbar/panel_status > "$PANEL_FIFO" &

~/.config/lemonbar/panel_lemon < "$PANEL_FIFO" \
     | lemonbar -a 32 \
           -g "$PANEL_GEOMETRY" \
           -f "$FONT1" \
           -f "$FONT2" \
           -B "$FOREGROUND_COLOR" \
           -F "$BACKGROUND_COLOR" \
           | sh &
wait
