# ~/.bash_logout: executed by bash(1) when login shell exits.
[ -n "$SSH_AUTH_SOCK" ] && [ -n "$SSH_AGENT_PID" ] && 2>&1 >/dev/null ps -p "$SSH_AGENT_PID" && readlink -e "/proc/$SSH_AGENT_PID/exe" | 2>&1 >/dev/null grep -E '.*ssh-agent$' && kill "$SSH_AGENT_PID"
[ "$SHLVL" = 1 ] && [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
unset HISTFILE
HISTSIZE=0 && exit

