# vi: ft=sh sts=2 ts=2 sw=2 et
# This file targets bash 3, guarding 4.

SOURCE_TRY() {
  [[ -f "$1" ]] && . "$1" && return 0
  return 1
}

SOURCE_FIRST () {
  while [[ $# -gt 0 ]]; do
     SOURCE_TRY "$1" && return 0
    shift
  done
  return 1
}

shopt_enabled=(
  # glob
  dotglob
  nocaseglob
  extglob                  #  strange quanitfiers with groups, needed for completitions

  # history
  cmdhist                  # put multiline commands into history
  histappend
  histverify

  # strangely custom
  cdspell
  gnu_errfmt
  no_empty_cmd_completion
  
  # defaults
  expand_aliases
  extquote
  interactive_comments
  progcomp
  promptvars
  checkwinsize    #  DANGER: update LINES and COLUMNS after each command
)

shopt_disabled=(
  # turned off defaults
  hostcomplete    #  triggers on @
  cdable_vars     #  if cd arg does not match, search env vars (was $ hard to type?)
  sourcepath

  # default offs
  failglob                 # don't pass failed globs
  execfail
  huponexit
  lithist
  mailwarn
  nocasematch
  nullglob
  shift_verbose
  xpg_echo
)


if [[ "$BASH_VERSINFO" -ge 4 ]]; then
  shoptions+=(
    checkhash
    checkjobs
    dirspell
    complete_fullquote
    lastpipe
  )
  shopt_disabled+=(
    globstar
    direxpand
  )
fi

shopt -s ${shopt_enabled[@]}
shopt -u ${shopt_disabled[@]}
unset shopt_enabled shopt_disabled

# http://wiki.bash-hackers.org/scripting/bashchanges
set -o vi noclobber

. ~/.config/bash/git.bash
. ~/.config/bash/prompt.bash
. ~/.config/bash/aliases.bash

SOURCE_TRY ~/.config/bash/os-aliases.bash
SOURCE_TRY ~/.config/bash/buku-completion.bash
#  SOURCE_TRY ~/.fzf/shell/completion.bash 2>/dev/null  # broken
 SOURCE_TRY ~/.fzf/shell/key-bindings.bash 2>/dev/null
 
# eval "$(dircolors -b ~/.config/bash/dircolors/dircolors.256dark) 2>/dev/null >/dev/null"

[[ -z "$HOSTNAME" ]] && HOSTNAME="$(hostname)"
HOSTIDENT="$(echo -n "$HOSTNAME" | sed 's/\..*//')"
 SOURCE_TRY ~/.config/bash/hosts/"${HOSTIDENT}.sh"
 SOURCE_TRY ~/.config/bash/hosts/"${HOSTIDENT}.private.sh"
 SOURCE_TRY ~/.config/bash/hosts/local.private.sh
unset HOSTIDENT

