#!/bin/bash

bspc config wm_name                 LG3D
bspc config border_width            2
bspc config window_gap              8
bspc config bottom_padding          0
bspc config top_padding             0
bspc config left_padding            0
bspc config right_padding           0
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config history_aware_focus     true
bspc config remove_disabled_monitor true
bspc config click_to_focus          true
bspc config focused_border_color    '#F5497D'

n="$(bspc rule --list | grep -c .)"
for ((i = 0; i < n; ++i)); do bspc rule --remove head; done
unset i n

bspc monitor --reset-desktops a b 

bspc rule --add gifview                   focus=true     state=floating center=true
bspc rule --add kupfer.py                 focus=true     state=floating center=true
bspc rule --add liferea                   focus=true     private=true
bspc rule --add Pavucontrol               focus=true     state=floating center=true
bspc rule --add qjackctl                  focus=true     state=floating
bspc rule --add FLTK                      focus=true     state=floating
bspc rule --add skype                     focus=true     state=floating
bspc rule --add sxiv                      focus=true     state=floating center=true fullscreen=true
bspc rule --add Thunar                    focus=true     state=floating follow=true
bspc rule --add transmission-gtk          focus=true     state=floating follow=true
bspc rule --add Transmission-remote-gtk   focus=true     state=floating follow=true
bspc rule --add vlc                       focus=true     state=floating
bspc rule --add xsensors                  focus=true     state=floating sticky=true
bspc rule --add Firefox                   state=tiled    focused=off
bspc rule --add Firefox:Dialog            state=floating
bspc rule --add Dwb                       state=tiled    focused=off
bspc rule --add Geary                     state=tiled    center=on
bspc rule --add Quirky                    state=tiled
bspc rule --add mpv                       state=floating
bspc rule --add Budgie                    state=floating
bspc rule --add gl                        state=floating
bspc rule --add Gimp                      state=tiled
bspc rule --add Nautilus                  state=floating
bspc rule --add Acroread                  state=floating
bspc rule --add Pinentry                  state=floating
bspc rule --add Wicd-client.py            state=floating center=true    sticky=true
bspc rule --add jetbrains-idea-ce         state=tiled    desktop=^java  private=true
bspc rule --add sun-awt-X11-XDialogPeer   state=floating
bspc rule --add sun-awt-X11-XFramePeer    state=floating
bspc rule --add TeamViewer.exe            state=floating
bspc rule --add com.ypcrts.AppMainFX   state=floating center=true    sticky=true
bspc rule --add Processed                 state=floating center=true    sticky=true
bspc rule --add Tk                        state=floating center=true    sticky=true
bspc rule --add Pidgin                    state=floating center=true
bspc rule --add Display                   state=floating
bspc rule --add *:sun-awt-X11-XDialogPeer state=floating
bspc rule --add *:sun-awt-X11-XFramePeer  state=floating
bspc rule --add Screenkey                 manage=off

# Firefox modal windows
bspc rule --add Cookies                   focus=true     state=floating
bspc rule --add Places                    focus=true     state=floating
bspc rule --add Toplevel                  focus=true     state=floating

./panel &
