# Source scripts in /etc/X11/xinit/xinitrc.d/
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# set environment variables
for f in /etc/profile  ~/.profile; do
    [ -r "$f" ] && . "$f"
done
unset f

/usr/bin/xrdb -merge ~/.Xresources

# /usr/bin/setxkbmap -option terminate:ctrl_alt_bksp
~/bin/fixkeys

#repeat rate
/usr/bin/xset r rate 300 20

/usr/bin/xsetroot -cursor_name left_ptr &

# needed for firefox OMTC on bspwm
export MOZ_USE_OMTC=1

#java
export _JAVA_AWT_WM_NONREPARENTING=1 JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
/usr/bin/wmname LG3D &

export SXHKD_SHELL=dash

# fontz
#if [ -f /usr/local/share/fonts ]; then
#    xset +fp /usr/local/share/fonts
#    xset fp rehash
#    fc-cache -f
#fi
#
. ~/.screenlayout/current.sh &
# ~/bin/feh-bgrotate --once &
#/usr/bin/compton &
#~/bin/redshift-run &
#~/bin/thinktouchpad off &
#/usr/bin/xscreensaver -no-splash &
dunst &
sxhkd &
exec bspwm >~/.local/bspwm.log 2>&1

# vim: set ft=sh tw=0 ts=4 sw=4 sts=2 fdm=marker fmr={{{,}}} et:
