#!/bin/sh
# toggle the rodent

# https://bitbucket.org/jasonwryan/centurion/src/120ca5085493f49e6ed0c3d42ef7992d8010e086/Scripts/mouse?at=default 

set -x
dimensions=$(xdpyinfo  | sed -rne 's/.*[Dd]imen.*:\s+([0-9]+)x([0-9]+).*/\1 \2/p')
res_x=$(echo "$dimensions" | awk '{print $1; exit}');
res_y=$(echo "$dimensions" | awk '{print $2; exit}');
unset dimensions

rat="$(xinput --list | sed -n -r -e 's/.*id=([0-9]+)\s+[\[](slave\s+pointer|[Mm]ouse).*/\1/p')"
trackpoint="$(xinput --list | sed -n -r -e 's/.*TrackPoint\s+id=([0-9]+)\s+\[.*/\1/p')"
xdotool_can="$(command -V xdotool 2>/dev/null >/dev/null; echo $?)"
cmd=

case $1 in
  on)
    if [ -n "$trackpoint" ]; then
      xinput enable "$trackpoint" 2>/dev/null >/dev/null
    else 
      for x in $rat
      do
        xinput enable "$x" 2>/dev/null >/dev/null
      done
    fi
    if [ -n "$xdotool_can" ]; then
      xdotool mousemove "$((res_x/2))" "$((res_y/2))"
    fi
    ;;
  off)
      for x in $rat
      do
        xinput disable "$x" 2>/dev/null >/dev/null
      done
      if [ -n "$xdotool_can" ]; then
        xdotool mousemove "$res_x" "$res_y"
      fi
    ;;
  *) printf '%s %s\n' $0 'on OR off…'; exit 1
    ;;
esac

